# cluster_config.yml - cluster configuration
__default__:
    account: sansam-lab
    partition: serial
    time: 08:00:00 # time limit for each job
    cpus-per-task: 2
    mem: 16G
    output: results/logs/slurm-%x.%A.%a.log
    error: results/errors/slurm-%x.%A.%a.err

merge_technical_replicates:
    cpus-per-task: 8
    mem: 64G
    cores: 8
    name: "{rule}.{wildcards.sample}"
    output: results/logs/{rule}.{wildcards.sample}.slurm-%x.%A.%a.log
    error: results/errors/{rule}.{wildcards.sample}.slurm-%x.%A.%a.err

call_narrow_peaks_with_macs2:
    cpus-per-task: 2
    mem: 16G
    cores: 12
    name: "{rule}.{wildcards.sample}"
    output: results/logs/{rule}.{wildcards.sample}.slurm-%x.%A.%a.log
    error: results/errors/{rule}.{wildcards.sample}.slurm-%x.%A.%a.err

downsample_min_read_counts:
    cpus-per-task: 8
    mem: 64G
    cores: 8
    name: "{rule}.{wildcards.sample}"
    output: results/logs/{rule}.{wildcards.sample}.slurm-%x.%A.%a.log
    error: results/errors/{rule}.{wildcards.sample}.slurm-%x.%A.%a.err

merged_downsampled_bams:
    cpus-per-task: 8
    mem: 64G
    cores: 8
    name: "{rule}.{wildcards.sample}"
    output: results/logs/{rule}.{wildcards.sample}.slurm-%x.%A.%a.log
    error: results/errors/{rule}.{wildcards.sample}.slurm-%x.%A.%a.err
    
